services:  

  application:
    container_name: rest-service-container
    image: rest-service-image
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - rest-service-volume:/var/lib/postgresql/data

volumes:
  rest-service-volume:
    name: rest-service-volume